version: '3.7'

services:
  web:
    build: ./
    command: gunicorn -w 4 -b :8000 "app:create_app()"
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env